"""empty message

Revision ID: 8017d346baa4
Revises: 81c4fbc5cbd1
Create Date: 2020-04-16 21:54:06.705611

"""

# revision identifiers, used by Alembic.
revision = '8017d346baa4'
down_revision = '81c4fbc5cbd1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('id_number', sa.String(length=18), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_users_ID_number'), 'users', ['ID_number'], unique=True)
    op.drop_index('ix_users_ID_number', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_ID_number', 'users', ['ID_number'], unique=1)
    op.drop_index(op.f('ix_users_ID_number'), table_name='users')
    op.drop_table('students')
    # ### end Alembic commands ###
