"""empty message

Revision ID: 883a886053af
Revises: 7aef7b7d7cf0
Create Date: 2020-04-03 18:06:28.745679

"""

# revision identifiers, used by Alembic.
revision = '883a886053af'
down_revision = '7aef7b7d7cf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ID_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_ID_number'), 'users', ['ID_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_ID_number'), table_name='users')
    op.drop_column('users', 'ID_number')
    # ### end Alembic commands ###
