"""empty message

Revision ID: ed902200ee87
Revises: b584db62a855
Create Date: 2020-04-19 21:50:21.181009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed902200ee87'
down_revision = 'b584db62a855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ID_number'), ['ID_number'], unique=True)
        batch_op.drop_index('ix_users_ID_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_ID_number', ['ID_number'], unique=1)
        batch_op.drop_index(batch_op.f('ix_users_ID_number'))

    op.drop_table('follow')
    # ### end Alembic commands ###
