"""last

Revision ID: f4571b811bf0
Revises: 
Create Date: 2020-04-21 21:09:29.226367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4571b811bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ID_number'), ['ID_number'], unique=True)
        batch_op.drop_index('ix_users_ID_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_ID_number', ['ID_number'], unique=1)
        batch_op.drop_index(batch_op.f('ix_users_ID_number'))

    # ### end Alembic commands ###
